application: cerewt
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on
- remote_api: on

handlers:
- url: /favicon\.ico
  static_files: media/img/favicon.ico
  upload: media/img/favicon.ico

- url: /media
  static_dir: media

- url: /.*
  script: test.py
