application: cerewt
version: 1
runtime: python
api_version: 1

builtins:
- appstats: on
- datastore_admin: on
- remote_api: on

handlers:
- url: /favicon\.ico
  static_files: media/img/favicon.ico
  upload: media/img/favicon.ico

- url: /media
  static_dir: media

#- url: /stats.*
#  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

- url: /.*
  script: main.py

admin_console:
  pages:
  - name: Appstats
    url: /_ah/stats
